version: '3.8'

services:
  server:
    image: golang:1.20.4-alpine
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    entrypoint: /app/scripts/start.sh
    ports:
      - 4001:4001
